AceGenericBundle_index:
    pattern:  /
    defaults: { _controller: AceGenericBundle:Default:index }

AceGenericBundle_user:
    pattern:  /user/{user}
    defaults: { _controller: AceGenericBundle:Default:user }

AceGenericBundle_project:
    pattern:  /sketch:{id}
    defaults: { _controller: AceGenericBundle:Default:project }

AceGenericBundle_wiselib_project:
    pattern:  /edit:{project_name}_app.cpp?project_id={id}
    defaults: { _controller: AceGenericBundle:Default:edit }
    requirements:
       project_name: "[a-zA-Z0-9\-_\/.]+"

AceGenericBundle_edit:
    pattern:  /edit:{fpath}
    defaults: { _controller: AceGenericBundle:Default:edit }
    requirements:
       fpath: "[a-zA-Z0-9\-_\/. ]+"

AceGenericBundle_projectfiles:
    pattern:  /files
    defaults: { _controller: AceGenericBundle:Default:projectfiles }
    requirements:
       _method:  POST

AceGenericBundle_embed_project:
    pattern:  /embed/sketch:{id}
    defaults: { _controller: AceGenericBundle:Default:project, embed:true }

AceGenericBundle_libraries:
    pattern: /libraries
    defaults: {_controller: AceGenericBundle:Default:libraries }

AceGenericBundle_example:
    pattern: /example/{library}/{example}/{url}
    defaults: {_controller: AceGenericBundle:Default:example }
    requirements:
        url: ".+"

AceGenericBundle_boards:
    pattern:  /boards
    defaults: { _controller: AceGenericBundle:Default:boards}

AceGenericBundle_embedded_compilerflasher_js:
    pattern:  /embed/compilerflasher.js
    defaults: { _controller: AceGenericBundle:Default:embeddedCompilerFlasherJavascript }
