-- phpMyAdmin SQL Dump
-- version 3.4.10.1deb1
-- http://www.phpmyadmin.net
--

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

-- --------------------------------------------------------

--
-- Table structure for table `Board`
--

CREATE TABLE IF NOT EXISTS `Board` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `owner_id` int(11) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `description` varchar(500) NOT NULL,
  `upload` varchar(300) NOT NULL,
  `bootloader` varchar(300) NOT NULL,
  `build` varchar(300) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_999704437E3C61F9` (`owner_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=27 ;

--
-- Dumping data for table `Board`
--

INSERT INTO `Board` (`id`, `owner_id`, `name`, `description`, `upload`, `bootloader`, `build`) VALUES
(1, NULL, 'Arduino Uno', 'The Uno is the reference model for the Arduino platform. It has 14 digital input/output pins (of which 6 can be used as PWM outputs), 6 analog inputs, a 16 MHz ceramic resonator, a USB connection, a power jack, an ICSP header, and a reset button. It does not use the FTDI USB-to-serial driver chip. Instead, it features the Atmega16U2 (Atmega8U2 up to version R2) programmed as a USB-to-serial converter.', '{"protocol":"arduino","maximum_size":"32256","speed":"115200"}', '{"low_fuses":"0xff","high_fuses":"0xde","extended_fuses":"0x05","path":"optiboot","file":"optiboot_atmega328.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', '{"mcu":"atmega328p","f_cpu":"16000000L","core":"arduino","variant":"standard"}'),
(2, NULL, 'Arduino Duemilanove w/ ATmega328', 'Around March 1st, 2009, the Duemilanove started to ship with the ATmega328p instead of the ATmega168. The ATmega328 has 32 KB, (also with 2 KB used for the bootloader).', '{"protocol":"arduino","maximum_size":"30720","speed":"57600"}', '{"low_fuses":"0xff","high_fuses":"0xda","extended_fuses":"0x05","path":"atmega","file":"ATmegaBOOT_168_atmega328.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', '{"mcu":"atmega328p","f_cpu":"16000000L","core":"arduino","variant":"standard"}'),
(3, NULL, 'Arduino Diecimila or Duemilanove w/ ATmega168', 'The Duemilanove automatically selects the appropriate power supply (USB or external power), eliminating the need for the power selection jumper found on previous boards. It also adds an easiest to cut trace for disabling the auto-reset, along with a solder jumper for re-enabling it.', '{"protocol":"arduino","maximum_size":"14336","speed":"19200"}', '{"low_fuses":"0xff","high_fuses":"0xdd","extended_fuses":"0x00","path":"atmega","file":"ATmegaBOOT_168_diecimila.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', '{"mcu":"atmega168","f_cpu":"16000000L","core":"arduino","variant":"standard"}'),
(4, NULL, 'Arduino Nano w/ ATmega328', 'The Arduino Nano is an all-in-one, compact design for use in breadboards. Version 3.0 has an ATmega328.', '{"protocol":"arduino","maximum_size":"30720","speed":"57600"}', '{"low_fuses":"0xff","high_fuses":"0xda","extended_fuses":"0x05","path":"atmega","file":"ATmegaBOOT_168_atmega328.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', '{"mcu":"atmega328p","f_cpu":"16000000L","core":"arduino","variant":"eightanaloginputs"}'),
(5, NULL, 'Arduino Nano w/ ATmega168', 'Older Arduino Nano with ATmega168 instead of the newer ATmega328.', '{"protocol":"arduino","maximum_size":"14336","speed":"19200"}', '{"low_fuses":"0xff","high_fuses":"0xdd","extended_fuses":"0x00","path":"atmega","file":"ATmegaBOOT_168_diecimila.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', '{"mcu":"atmega168","f_cpu":"16000000L","core":"arduino","variant":"eightanaloginputs"}'),
(6, NULL, 'Arduino Mega 2560 or Mega ADK', 'The Mega 2560 is an update to the Arduino Mega, which it replaces. It features the Atmega2560, which has twice the memory, and uses the ATMega 8U2 for USB-to-serial communication.', '{"protocol":"stk500v2","maximum_size":"258048","speed":"115200"}', '{"low_fuses":"0xff","high_fuses":"0xd8","extended_fuses":"0xfd","path":"stk500v2","file":"stk500boot_v2_mega2560.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', '{"mcu":"atmega2560","f_cpu":"16000000L","core":"arduino","variant":"mega"}'),
(7, NULL, 'Arduino Mega (ATmega1280)', 'A larger, more powerful Arduino board. Has extra digital pins, PWM pins, analog inputs, serial ports, etc. The original Arduino Mega has an ATmega1280 and an FTDI USB-to-serial chip.', '{"protocol":"arduino","maximum_size":"126976","speed":"57600"}', '{"low_fuses":"0xff","high_fuses":"0xda","extended_fuses":"0xf5","path":"atmega","file":"ATmegaBOOT_168_atmega1280.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', '{"mcu":"atmega1280","f_cpu":"16000000L","core":"arduino","variant":"mega"}'),
(8, NULL, 'Arduino Leonardo', 'The Leonardo differs from all preceding boards in that the ATmega32u4 has built-in USB communication, eliminating the need for a secondary processor. This allows the Leonardo to appear to a connected computer as a mouse and keyboard, in addition to a virtual (CDC) serial / COM port.', '{"protocol":"avr109","maximum_size":"28672","speed":"57600", "disable_flushing":"true"}', '{"low_fuses":"0xff","high_fuses":"0xd8","extended_fuses":"0xcb","path":"caterina","file":"Caterina-Leonardo.hex","unlock_bits":"0x3F","lock_bits":"0x2F"}', '{"vid":"0x2341","pid":"0x8036","mcu":"atmega32u4","f_cpu":"16000000L","core":"arduino","variant":"leonardo"}'),
(9, NULL, 'Arduino Mini w/ ATmega328', 'The Mini is a compact Arduino board, intended for use on breadboards and when space is at a premium. This version has an ATmega328.', '{"protocol":"stk500","maximum_size":"28672","speed":"115200"}', '{"low_fuses":"0xff","high_fuses":"0xd8","extended_fuses":"0x05","path":"optiboot","file":"optiboot_atmega328-Mini.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', '{"mcu":"atmega328p","f_cpu":"16000000L","core":"arduino","variant":"eightanaloginputs"}'),
(10, NULL, 'Arduino Mini w/ ATmega168', 'Older Arduino Mini version with the ATmega168 microcontroller.', '{"protocol":"arduino","maximum_size":"14336","speed":"19200"}', '{"low_fuses":"0xff","high_fuses":"0xdd","extended_fuses":"0x00","path":"atmega","file":"ATmegaBOOT_168_ng.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', '{"mcu":"atmega168","f_cpu":"16000000L","core":"arduino","variant":"eightanaloginputs"}'),
(11, NULL, 'Arduino Ethernet', 'The Ethernet differs from other boards in that it does not have an onboard USB-to-serial driver chip, but has a Wiznet Ethernet interface. This is the same interface found on the Ethernet shield.', '{"protocol":"arduino","maximum_size":"32256","speed":"115200"}', '{"low_fuses":"0xff","high_fuses":"0xde","extended_fuses":"0x05","path":"optiboot","file":"optiboot_atmega328.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', '{"mcu":"atmega328p","f_cpu":"16000000L","core":"arduino","variant":"standard"}'),
(12, NULL, 'Arduino Fio', 'An Arduino intended for use as a wireless node. Has a header for an XBee radio, a connector for a LiPo battery, and a battery charging circuit.', '{"protocol":"arduino","maximum_size":"30720","speed":"57600"}', '{"low_fuses":"0xff","high_fuses":"0xda","extended_fuses":"0x05","path":"atmega","file":"ATmegaBOOT_168_atmega328_pro_8MHz.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', '{"mcu":"atmega328p","f_cpu":"8000000L","core":"arduino","variant":"eightanaloginputs"}'),
(13, NULL, 'Arduino Pro or Pro Mini (5V, 16 MHz) w/ ATmega328', 'The Arduino Pro is intended for semi-permanent installation in objects or exhibitions. The board comes without pre-mounted headers, allowing the use of various types of connectors or direct soldering of wires. The pin layout is compatible with Arduino shields.  The Arduino Pro Mini pin layout is compatible with the Arduino Mini.', '{"protocol":"arduino","maximum_size":"30720","speed":"57600"}', '{"low_fuses":"0xFF","high_fuses":"0xDA","extended_fuses":"0x05","path":"atmega","file":"ATmegaBOOT_168_atmega328.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', '{"mcu":"atmega328p","f_cpu":"16000000L","core":"arduino","variant":"standard"}'),
(14, NULL, 'Arduino Pro or Pro Mini (5V, 16 MHz) w/ ATmega168', 'The Arduino Pro is intended for semi-permanent installation in objects or exhibitions. The board comes without pre-mounted headers, allowing the use of various types of connectors or direct soldering of wires. The pin layout is compatible with Arduino shields.  The Arduino Pro Mini pin layout is compatible with the Arduino Mini.', '{"protocol":"arduino","maximum_size":"14336","speed":"19200"}', '{"low_fuses":"0xff","high_fuses":"0xdd","extended_fuses":"0x00","path":"atmega","file":"ATmegaBOOT_168_diecimila.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', '{"mcu":"atmega168","f_cpu":"16000000L","core":"arduino","variant":"standard"}'),
(15, NULL, 'Arduino Pro or Pro Mini (3.3V, 8 MHz) w/ ATmega328', 'The Arduino Pro is intended for semi-permanent installation in objects or exhibitions. The board comes without pre-mounted headers, allowing the use of various types of connectors or direct soldering of wires. The pin layout is compatible with Arduino shields.  The Arduino Pro Mini pin layout is compatible with the Arduino Mini.', '{"protocol":"arduino","maximum_size":"30720","speed":"57600"}', '{"low_fuses":"0xFF","high_fuses":"0xDA","extended_fuses":"0x05","path":"atmega","file":"ATmegaBOOT_168_atmega328_pro_8MHz.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', '{"mcu":"atmega328p","f_cpu":"8000000L","core":"arduino","variant":"standard"}'),
(16, NULL, 'Arduino Pro or Pro Mini (3.3V, 8 MHz) w/ ATmega168', 'The Arduino Pro is intended for semi-permanent installation in objects or exhibitions. The board comes without pre-mounted headers, allowing the use of various types of connectors or direct soldering of wires. The pin layout is compatible with Arduino shields.  The Arduino Pro Mini pin layout is compatible with the Arduino Mini.', '{"protocol":"arduino","maximum_size":"14336","speed":"19200"}', '{"low_fuses":"0xc6","high_fuses":"0xdd","extended_fuses":"0x00","path":"atmega","file":"ATmegaBOOT_168_pro_8MHz.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', '{"mcu":"atmega168","f_cpu":"8000000L","core":"arduino","variant":"standard"}'),
(17, NULL, 'TinyDuino', 'TinyDuino is a completely Arduino compatible platform smaller than the size of a quarter, yet with all the power and functionality of the Arduino Uno board - including Shield Support!', '{"protocol":"arduino","maximum_size":"30720","speed":"57600"}', '{"low_fuses":"0xFF","high_fuses":"0xDA","extended_fuses":"0x05","path":"atmega","file":"ATmegaBOOT_168_atmega328_pro_8MHz.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', '{"mcu":"atmega328p","f_cpu":"8000000L","core":"arduino","variant":"standard"}'),
(18, NULL, 'Arduino Micro', 'The Arduino Micro is a microcontroller board based on the ATmega32u4 (datasheet), developed in conjunction with Adafruit. It contains everything needed to support the microcontroller; simply connect it to a computer with a micro USB cable to get started. It has a form factor that enables it to be easily placed on a breadboard.', ' {"protocol":"avr109","maximum_size":"28672","speed":"57600","disable_flushing":"true"}', ' {"low_fuses":"0xff","high_fuses":"0xd8","extended_fuses":"0xcb","path":"caterina","file":"Caterina-Micro.hex","unlock_bits":"0x3F","lock_bits":"0x2F"}', ' {"mcu":"atmega32u4","f_cpu":"16000000L","vid":"0x2341","pid":"0x8037","core":"arduino","variant":"micro"}'),
(19, NULL, 'Arduino Esplora (untested)', 'Arduino Esplora is a microcontroller board derived from the Arduino Leonardo. The Esplora differs from all preceding Arduino boards in that it provides a number of built-in, ready-to-use setof onboard sensors for interaction. It has onboard sound and light outputs, and several input sensors, including a joystick, a slider, a temperature sensor, an accelerometer, a microphone, and a light sensor.', ' {"protocol":"avr109","maximum_size":"28672","speed":"57600","disable_flushing":"true"}', ' {"low_fuses":"0xff","high_fuses":"0xd8","extended_fuses":"0xcb","path":"caterina","file":"Caterina-Esplora.hex","unlock_bits":"0x3F","lock_bits":"0x2F"}', ' {"mcu":"atmega32u4","f_cpu":"16000000L","vid":"0x2341","pid":"0x803C","core":"arduino","variant":"leonardo"}'),
(20, NULL, ' LilyPad Arduino USB (untested)', 'The LilyPad USB is replacing the classic ATMega328 with the new ATMega32U4. LilyPad is a wearable e-textile technology developed by Leah Buechley and cooperatively designed by Leah and SparkFun. Each LilyPad was creatively designed to have large connecting pads to allow them to be sewn into clothing. Various input, output, power, and sensor boards are available. They''re even washable!', ' {"protocol":"avr109","maximum_size":"28672","speed":"57600","disable_flushing":"true"}', ' {"low_fuses":"0xff","high_fuses":"0xd8","extended_fuses":"0xce","path":"caterina-LilyPadUSB","file":"Caterina-LilyPadUSB.hex","unlock_bits":"0x3F","lock_bits":"0x2F"}', ' {"mcu":"atmega32u4","f_cpu":"8000000L","vid":"0x1B4F","pid":"0x9208","core":"arduino","variant":"leonardo"}'),
(21, NULL, ' LilyPad Arduino w/ ATmega328 (untested)', 'LilyPad is a wearable e-textile technology developed by Leah Buechley and cooperatively designed by Leah and SparkFun. Each LilyPad was creatively designed to have large connecting pads to allow them to be sewn into clothing. Various input, output, power, and sensor boards are available. They''re even washable!', ' {"protocol":"arduino","maximum_size":"30720","speed":"57600"}', ' {"low_fuses":"0xFF","high_fuses":"0xDA","extended_fuses":"0x05","path":"atmega","file":"ATmegaBOOT_168_atmega328_pro_8MHz.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', ' {"mcu":"atmega328p","f_cpu":"8000000L","core":"arduino","variant":"standard"}'),
(22, NULL, ' LilyPad Arduino w/ ATmega168 (untested)', 'LilyPad is a wearable e-textile technology developed by Leah Buechley and cooperatively designed by Leah and SparkFun. Each LilyPad was creatively designed to have large connecting pads to allow them to be sewn into clothing. Various input, output, power, and sensor boards are available. They''re even washable!', ' {"protocol":"arduino","maximum_size":"14336","speed":"19200"}', ' {"low_fuses":"0xe2","high_fuses":"0xdd","extended_fuses":"0x00","path":"lilypad","file":"LilyPadBOOT_168.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', ' {"mcu":"atmega168","f_cpu":"8000000L","core":"arduino","variant":"standard"}'),
(23, NULL, ' Arduino BT w/ ATmega328 (untested)', 'The Arduino BT is a microcontroller board originally was based on the ATmega168, but now is supplied with the 328. It supports wireless serial communication over bluetooth (but is not compatible with Bluetooth headsets or other audio devices). It contains everything needed to support the microcontroller and can be programmed wirelessly over the Bluetooth connection.', ' {"protocol":"arduino","maximum_size":"28672","speed":"19200","disable_flushing":"true"}', ' {"low_fuses":"0xff","high_fuses":"0xd8","extended_fuses":"0x05","path":"bt","file":"ATmegaBOOT_168_atmega328_bt.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', ' {"mcu":"atmega328p","f_cpu":"16000000L","core":"arduino","variant":"eightanaloginputs"}'),
(24, NULL, ' Arduino BT w/ ATmega168 (untested)', 'The Arduino BT is a microcontroller board originally was based on the ATmega168, but now is supplied with the 328. It supports wireless serial communication over bluetooth (but is not compatible with Bluetooth headsets or other audio devices). It contains everything needed to support the microcontroller and can be programmed wirelessly over the Bluetooth connection.', ' {"protocol":"arduino","maximum_size":"14336","speed":"19200","disable_flushing":"true"}', ' {"low_fuses":"0xff","high_fuses":"0xdd","extended_fuses":"0x00","path":"bt","file":"ATmegaBOOT_168.hex","unlock_bits":"0x3F","lock_bits":"0x0F"}', ' {"mcu":"atmega168","f_cpu":"16000000L","core":"arduino","variant":"eightanaloginputs"}'),
(25, NULL, 'Digispark (Tiny Core)', 'DigiSpark', '{"maximum_size":"6010","using":"digispark", "protocol":"digispark", "speed":"1000"}', '', '{"mcu":"attiny85","f_cpu":"16500000L","core":"digispark", "variant":"dummy"}'),
(26, NULL, 'Arno', 'Learning the basics of electronics and programming is challenging. Learning them while juggling piles of tiny parts, jumper wires, and breadboards is even more difficult. With the Arno, we''ve gotten rid of the piles of parts. Everything you need to learn Arduino and complete interesting projects in already built in. The board comes fully assembled, ready to plug in with the included USB cable. Focus on learning how the circuits work and learning the Arduino language, then tackle the rest.', '{"protocol":"avr109","maximum_size":"28672","speed":"57600", "disable_flushing":"true"}', '{"low_fuses":"0xff","high_fuses":"0xd8","extended_fuses":"0xcb","path":"caterina","file":"Caterina-Leonardo.hex","unlock_bits":"0x3F","lock_bits":"0x2F"}', '{"vid":"0x2341","pid":"0x8036","mcu":"atmega32u4","f_cpu":"16000000L","core":"arduino","variant":"leonardo"}');
